brasero-project: include libxml/xmlerror.h for xmlError
Explicitly include required libxml headers, instead of
relying on GStreamer's headers to include them. Fixes
brasero-project.c:2616:2: error: unknown type name ‘xmlError’